#!/bin/bash
# script to run Dsuite
# do NOT run in conda environment

# input vcf-file can be generated from slim-output using the command:
# /opt/software/bcftools-1.20/bin/bcftools view --threads 10 --min-alleles 2 --max-alleles 2 --exclude-types indels -O z hybridspeciation_1000G.vcf -o hybridspeciation_1000G.biallelic.vcf.gz &

# the input populations tree file can be generated, for example, as follows, with SambaR:
# calcpi()
# dxymat<- pops2matrix(plot_label=NULL,my_Breaks=NULL,nr_breaks=8,doplot=TRUE,myscore="ndiffpersite",zero_diagonal=FALSE,return_object=TRUE,dofilter=TRUE)
# getpoptree(doexport=TRUE,mymatrix=dxymat,exportlabel="Dxy",donj=FALSE,edgecolors=TRUE,mytype="phylogram",labelcex=1,mylwd=2.5,writetree=TRUE)
# This will generate a file called 'Poptree.Dxy.UPGMA.newick.txt', which can be used as input to the MYTREE flag.

# Alternatively, you can always use one of the population trees generated by the hudsonfst() function (when processing VCF_calcdist output)


#####################################
DSUITE=/opt/software/Dsuite/Build/Dsuite
DTOOLSPY=/opt/software/Dsuite/utils/dtools.py

MYTREE=Poptree_hybridsaddedmanually.txt
MYVCF=/home/mdejong/bearproject/snpfiles_NorthAmerica/NorthAmericamodern112.mysnps.thinned.50000.vcf.gz
POPFILE=/home/mdejong/bearproject/snpfiles_NorthAmerica/Dsuite/population_mapping.txt
# population should contain two columns (samplename and population/species name), tab-separated, population/species name of outgroup should be replaced with 'Outgroup'

MYPREFIX=Northamerica112
MYOUTGROUP=Black		# Outgroup population, NOT individual, correspond to name specified in input tree (in popfile.txt this population should be called 'Outgroup' 
#####################################

# Calculate D-statistics for all possible triplets (corresponding to phylogeny):
echo "Calculating D-statistics..."
$DSUITE Dtrios --tree=$MYTREE $MYVCF $POPFILE --out-prefix=${MYPREFIX}

# Calculate fb (D-statistics summed per branch):
echo "Calculating fb statistics..."
$DSUITE Fbranch $MYTREE ${MYPREFIX}_tree.txt > ${MYPREFIX}_Fbranch.txt

# Generate plot:
echo "Generating plot..."
$DTOOLSPY ${MYPREFIX}_Fbranch.txt $MYTREE --outgroup $MYOUTGROUP

echo "Done :-)"